spring:
  application:
    name: has-zk-app
  cloud:
    zookeeper:
      discovery:
        root: /zk-service
      connect-string: localhost:2181

server:
  port: 8181
management:
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: "*"